POST http://localhost:3000/aluno
Content-Type: application/json

{
    "nome": "Roberto",
    "turma": "2B",
    "notas": [
        {"disciplina": "matemática", "nota": 8},
        {"disciplina": "história", "nota": 9}
    ],
    "media": 8.5  
}

###

GET http://localhost:3000/alunos
Content-Type: application/json

###

PUT http://localhost:3000/aluno/411f9b97-2b08-4862-bc5d-6ca0a724e829
Content-Type: application/json

{
    "turma": "2Adf",
    "notas": [
        {"disciplina": "matemática", "nota": 8},
        {"disciplina": "história", "nota": 9}
    ],
    "media": 8.5  
}